This code is for sending an email when Front motion alert is raised.
It assumes that you propery created an email notifier and configured email access information.

var params = {
to: "recipient@email.com" /* STRING */,
body: "Front Motion detected" /* HTML */,
subject: eventData.description + " at " + eventTime/* STRING */,
from:"sender@email.com" /* STRING */,
};

// no return
Things["YourNotifier"].SendMessage(params);
